### ISSUE TITLE
Issues when testing the IMC-PT-SparseGM 

### ISSUE THREAD

**Issue by gtan45** [Thinklab-SJTU/ThinkMatch#65] opened 2024-01-08 01:19 UTC
I tried to run the experiments related to IMC-PT-SparseGM dataset by executing "experiments/ngmv2-afat/vgg16_ngmv2-afat-u_imcpt_50_stage1.yaml". 

When I run initially, I got the error "FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/pygmtools/data/IMC-PT-SparseGM.tar.gz'". 

Then I updated the version of the pygmtools to version "0.4.3" and re-run. Then I got the following issue "AssertionError: you should not change ROOT_DIR_IMG or ROOT_DIR_NPZ unless the data have been manually downloaded".

Suggestions on how to fix the above issue and run the experiments related to IMC-PT-SparseGM dataset will be much appreciated.

**Comment by ziao-guo** [comment] 2024-01-08 04:25
Typically, the dataset is automatically downloaded. However, it seems that some issues are causing the dataset not to be downloaded correctly. You can provide more error information to help determine the cause of the issue.
Alternatively, you are recommended to manually download the dataset. See the homepage of IMC-PT-SparseGM [here](https://github.com/Thinklab-SJTU/IMCPT-SparseGM-dataset).
Download and unzip the dataset and make sure it looks like `data/IMC-PT-SparseGM/annotations` and `data/IMC-PT-SparseGM/images`.

**Comment by gtan45** [comment] 2024-03-26 02:28
Thanks for the instructions. It worked well for the imcpt_50 dataset. 

But when trying to run imcpt_100 dataset, the following error keep occurring. Suggestions on how to fix the above issue and run the experiments related to imcpt_100 will be much appreciated.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_594776/3847300564.py in <module>
     17                      cfg.TRAIN.CLASS if x == 'train' else cfg.EVAL.CLASS,
     18                      cfg.PROBLEM.TYPE)
---> 19         for x in ('train', 'test')}
     20 dataloader = {x: get_dataloader(image_dataset[x], shuffle=True, fix_seed=(x == 'test'))
     21                   for x in ('train', 'test')}

/tmp/ipykernel_594776/3847300564.py in <dictcomp>(.0)
     17                      cfg.TRAIN.CLASS if x == 'train' else cfg.EVAL.CLASS,
     18                      cfg.PROBLEM.TYPE)
---> 19         for x in ('train', 'test')}
     20 dataloader = {x: get_dataloader(image_dataset[x], shuffle=True, fix_seed=(x == 'test'))
     21                   for x in ('train', 'test')}

/workspace/new/newn/ThinkMatch/src/dataset/data_loader.py in __init__(self, name, bm, length, using_all_graphs, cls, problem)
     35         self.problem_type = problem
     36         if problem != 'MGM3':
---> 37             self.img_num_list = self.bm.compute_img_num(self.classes)
     38         else:
     39             self.img_num_list = self.bm.compute_img_num(self.classes[0])

/opt/conda/lib/python3.7/site-packages/pygmtools/benchmark.py in compute_img_num(self, classes)
    354             if self.name != 'SPair71k':
    355                 for id in data_id:
--> 356                     if self.data_dict[id]['cls'] == clss:
    357                         cls_img_num += 1
    358                 num_list.append(cls_img_num)

KeyError: '70392907_4845953799'

**Comment by gtan45** [comment] 2024-03-26 02:33
Thanks a lot for the instructions. The dataset was downloaded as per the instructions and it was possible to run imcpt_50 dataset successfully.
However, when trying to run the imcpt_100 dataset the following error keep occurring. Suggestions on how to fix the error will be much appreciated.

KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_594776/3847300564.py in <module>
     17                      cfg.TRAIN.CLASS if x == 'train' else cfg.EVAL.CLASS,
     18                      cfg.PROBLEM.TYPE)
---> 19         for x in ('train', 'test')}
     20 dataloader = {x: get_dataloader(image_dataset[x], shuffle=True, fix_seed=(x == 'test'))
     21                   for x in ('train', 'test')}

/tmp/ipykernel_594776/3847300564.py in <dictcomp>(.0)
     17                      cfg.TRAIN.CLASS if x == 'train' else cfg.EVAL.CLASS,
     18                      cfg.PROBLEM.TYPE)
---> 19         for x in ('train', 'test')}
     20 dataloader = {x: get_dataloader(image_dataset[x], shuffle=True, fix_seed=(x == 'test'))
     21                   for x in ('train', 'test')}

ThinkMatch/src/dataset/data_loader.py in __init__(self, name, bm, length, using_all_graphs, cls, problem)
     35         self.problem_type = problem
     36         if problem != 'MGM3':
---> 37             self.img_num_list = self.bm.compute_img_num(self.classes)
     38         else:
     39             self.img_num_list = self.bm.compute_img_num(self.classes[0])

/opt/conda/lib/python3.7/site-packages/pygmtools/benchmark.py in compute_img_num(self, classes)
    354             if self.name != 'SPair71k':
    355                 for id in data_id:
--> 356                     if self.data_dict[id]['cls'] == clss:
    357                         cls_img_num += 1
    358                 num_list.append(cls_img_num)

KeyError: '70392907_4845953799'

**Comment by ziao-guo** [comment] 2024-03-26 02:55
It seems that something goes wrong in the data preprocessing stage.

Could you please provide the version of the pygmtools package you are using and how you run the imcpt_100 experiment? That will help detect the reason for the error.

**Comment by gtan45** [comment] 2024-03-26 03:14
The pygmtools pakcage version is pygmtools==0.3.8. Also, the imcpt_100 experiment was tried to run using python train_eval.py --cfg experiments/gcan-afat/vgg16_gcan-afat-i_imcpt_100_stage1.yaml. Thanks.

**Comment by ziao-guo** [comment] 2024-03-26 03:42
Thanks for the info, I found the problem.

Before you run the imcpt_100 experiment, you need to go to the `data/IMC-PT-SparseGM` directory and remove `train.json` and `test.json`, which are generated for imcpt_50. We will fix the bug in the later version of pygmtools.

Thanks for the issue!

**Comment by gtan45** [comment] 2024-03-26 04:14
Thanks.

**Comment by rogerwwww** [comment] 2024-07-17 15:37
I am closing this issue. Feel free to reopen it if the issue still exists.

**Closed by rogerwwww** 2024-07-17 15:37 UTC
