### ISSUE TITLE
ValueError: Mat 4 mopt wrong format, byteswapping problem?

### ISSUE THREAD

**Issue by fangcuiyun** [Thinklab-SJTU/ThinkMatch#50] opened 2022-07-26 01:25 UTC
I run train_eval.py by the code:
```python:
python train_eval.py --cfg experiments/vgg16_pca_willow.yaml
```
I have downloaded Willow Object dataset and pretrained models , and changed the pretrained path in vgg16_pca_willow.yaml.
But there was an errer:
```python:
Traceback (most recent call last):
  File "train_eval.py", line 258, in <module>
    for x in ('train', 'test')}
  File "train_eval.py", line 258, in <dictcomp>
    for x in ('train', 'test')}
  File "/opt/conda/lib/python3.7/site-packages/pygmtools/benchmark.py", line 41, in __init__
    data_set = eval(self.name)(self.sets, self.obj_resize, **args)
  File "/opt/conda/lib/python3.7/site-packages/pygmtools/dataset.py", line 431, in __init__
    self.process()
  File "/opt/conda/lib/python3.7/site-packages/pygmtools/dataset.py", line 570, in process
    annotations = self.__get_anno_dict(name, cls)
  File "/opt/conda/lib/python3.7/site-packages/pygmtools/dataset.py", line 587, in __get_anno_dict
    struct = sio.loadmat(mat_file.open('rb'))
  File "/opt/conda/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 226, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/opt/conda/lib/python3.7/site-packages/scipy/io/matlab/mio4.py", line 390, in get_variables
    hdr, next_position = self.read_var_header()
  File "/opt/conda/lib/python3.7/site-packages/scipy/io/matlab/mio4.py", line 346, in read_var_header
    hdr = self._matrix_reader.read_header()
  File "/opt/conda/lib/python3.7/site-packages/scipy/io/matlab/mio4.py", line 108, in read_header
    raise ValueError('Mat 4 mopt wrong format, byteswapping problem?')
ValueError: Mat 4 mopt wrong format, byteswapping problem?
```
Many appreciate if got any reply!

**Comment by 1115712590** [comment] 2022-09-15 13:18
It is strange that I cannot reproduce your problem. Did you build your environment manually? If so, maybe you could build your env with [Docker](https://github.com/Thinklab-SJTU/ThinkMatch#docker-recommended) and retry it.

**Comment by rogerwwww** [comment] 2022-10-23 14:11
I am closing this non-active issue. Feel free to reopen it if you still have any questions.

**Closed by rogerwwww** 2022-10-23 14:11 UTC
