### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

### ISSUE THREAD

**Issue by Lin-Yijie** [Thinklab-SJTU/ThinkMatch#32] opened 2021-11-19 13:18 UTC
Hi, I find the same error when setting GPUs in .yaml like:
```
 # available GPU ids
GPUS:
  - 0
  - 1
```
Has the code implemented the DataParallel for Multi-GPUs? Many appreciate if got any reply! @rogerwwww 

> I trained on two GPUs. where `yaml` as follows:
> 
> ```
> # available GPU ids
> GPUS:
>   - 0
>   - 1
> ```
> 
> But there was an error:
> 
> ```
> Traceback (most recent call last):
>   File "train_eval.py", line 309, in <module>
>     xls_wb=wb)
>   File "train_eval.py", line 99, in train_eval_model
>     outputs = model(inputs)
>   File "/home/pyenv/gm_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/pyenv/gm_env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 156, in forward
>     return self.gather(outputs, self.output_device)
>   File "/home/ThinkMatch/src/parallel/data_parallel.py", line 18, in gather
>     return gather(outputs, output_device, dim=self.dim)
>   File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 85, in gather
>     return gather_map(outputs)
>   File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 79, in gather_map
>     for k in out))
>   File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 79, in <genexpr>
>     for k in out))
>   File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 80, in gather_map
>     return type(out)(map(gather_map, zip(*outputs)))
>   File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 71, in gather_map
>     return concatenate(*outputs, device=target_device)
>   File "/home/ThinkMatch/src/sparse_torch/csx_matrix.py", line 458, in concatenate
>     indptr_offset += mat.indptr[-1]
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

_Originally posted by @Lin-Yijie in https://github.com/Thinklab-SJTU/ThinkMatch/issues/24#issuecomment-972428512_

**Comment by rogerwwww** [comment] 2021-11-19 14:10
I am closing this issue because it is a duplicate of https://github.com/Thinklab-SJTU/ThinkMatch/issues/24

**Closed by rogerwwww** 2021-11-19 14:10 UTC
